SET IDENTITY_INSERT [dbo].[TeaEntity] ON
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (2, 1, N'A1', N'Boba (big pearl) Jasmine Milk Tea', 1, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (4, 1, N'A2', N'Jelly jasmine Green Milk Tea', 1, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (5, 1, N'A3', N'Jelly jasmine Red Milk Tea', 1, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (8, 1, N'A4', N'Jade Lemon Green Team', 1, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (9, 1, N'A5', N'Honey Green Tea', 1, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (10, 1, N'A6', N'Yakult Red Tea', 1, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (12, 1, N'A7', N'Ceylon Red Tea Latte', 1, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (13, 1, N'A8', N'Jasmin Green Tea Latte', 1, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (14, 1, N'A9', N'Caramel Rea Tea Latte', 1, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (16, 1, N'A10', N'Boba (big pearl) Jasmine Milk Tea', 1, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (17, 1, N'A11', N'Jelly jasmine Green Milk Tea', 1, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (18, 1, N'A12', N'Ceylon Red Tea Latte', 1, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (20, 1, N'A13', N'Jelly jasmine Red Milk Tea', 1, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (21, 1, N'A14', N'Ceylon Red Tea Latte', 1, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (22, 1, N'A15', N'Jade Lemon Green Team', 1, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (1002, 1, N'B1', N'Jasmin Green Tea Latte', 2, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (1003, 1, N'B2', N'Honey Green Tea', 2, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (1004, 1, N'B3', N'Jelly jasmine Red Milk Tea', 2, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (1005, 1, N'B4', N'Boba (big pearl) Jasmine Milk Teailk Tea', 2, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (1006, 1, N'B5', N'Yakult Red Tea', 2, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (1007, 1, N'C1', N'Ceylon Red Tea Latte', 3, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (1008, 1, N'C2', N'Caramel Rea Tea Latte', 3, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (1009, 1, N'C3', N'Yakult Red Tea', 3, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (1010, 1, N'D1', N'Jasmin Green Tea Latte', 4, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (1011, 1, N'D2', N'Ceylon Red Tea Latte', 4, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (1012, 1, N'D3', N'Honey Green Tea', 4, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (1013, 1, N'E1', N'Boba (big pearl) Jasmine Milk Tea', 5, 90, 100)
INSERT INTO [dbo].[TeaEntity] ([Id], [Rating], [Code], [Name], [ItemId], [Regular], [Large]) VALUES (1014, 1, N'E2', N'Jelly jasmine Green Milk Tea', 5, 90, 100)
SET IDENTITY_INSERT [dbo].[TeaEntity] OFF
